---
version: '3.7'
services:
  python-boltons.proctor:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/proctor:delegated
    working_dir: /proctor
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
